/** 定时爬取种子列表；route 内按 domain+name 去重，先出现的 URL 优先保留 */
export type CrawlTargetSeed = { domain: string; url: string; name: string };

export const crawlTargetsSeed: CrawlTargetSeed[] = [
  { domain: "immigration", url: "https://www.canada.ca/en/immigration-refugees-citizenship.html", name: "加拿大移民局" },
  { domain: "immigration", url: "https://immi.homeaffairs.gov.au", name: "澳大利亚移民局" },
  { domain: "immigration", url: "https://www.ica.gov.sg", name: "新加坡移民局" },
  { domain: "immigration", url: "https://www.uscis.gov", name: "美国移民局" },
  { domain: "tax", url: "https://www.ird.gov.hk", name: "香港税务局" },
  { domain: "tax", url: "https://www.iras.gov.sg", name: "新加坡税务局" },
  { domain: "offshore", url: "https://www.cr.gov.hk", name: "香港公司注册处" },
  { domain: "offshore", url: "https://www.acra.gov.sg", name: "新加坡会计与企业管制局" },
  { domain: "banking", url: "https://www.hkma.gov.hk", name: "香港金融管理局" },
  { domain: "banking", url: "https://www.mas.gov.sg", name: "新加坡金融管理局" },
  { domain: "legal", url: "https://www.doj.gov.hk", name: "香港律政司" },
  { domain: "education", url: "https://www.educanada.ca", name: "加拿大留学" },
  { domain: "medical", url: "https://www.moh.gov.sg", name: "新加坡卫生部" },

  { domain: "immigration", url: "https://www.gov.uk/browse/visas-immigration", name: "英国移民局" },
  { domain: "immigration", url: "https://www.immigration.govt.nz", name: "新西兰移民局" },
  { domain: "immigration", url: "https://www.immd.gov.hk", name: "香港入境事务处" },
  { domain: "immigration", url: "https://www.malaysia-my-second-home.com", name: "马来西亚第二家园" },
  { domain: "immigration", url: "https://www.immigration.go.th", name: "泰国移民局" },
  { domain: "immigration", url: "https://www.mofa.go.jp/j_info/visit/visa", name: "日本签证信息" },
  { domain: "immigration", url: "https://www.hikorea.go.kr", name: "韩国移民局" },
  { domain: "immigration", url: "https://www.sef.pt/en", name: "葡萄牙移民局" },
  { domain: "immigration", url: "https://www.exteriores.gob.es", name: "西班牙移民信息" },
  { domain: "immigration", url: "https://www.government.nl/topics/immigration", name: "荷兰移民信息" },
  { domain: "immigration", url: "https://www.mii.gov.mt", name: "马耳他移民局" },
  { domain: "immigration", url: "https://www.uaevisaonline.ae", name: "阿联酋签证信息" },
  { domain: "immigration", url: "https://www.dubai.ae/en/business/setting-up", name: "迪拜自由区设立" },
  { domain: "immigration", url: "https://www.etias.com", name: "欧盟ETIAS入境系统" },
  { domain: "immigration", url: "https://www.schengenvisainfo.com", name: "申根签证信息" },
  { domain: "immigration", url: "https://www.henleyglobal.com", name: "护照指数Henley" },
  { domain: "immigration", url: "https://www.nomadgate.com", name: "数字游民移民指南" },
  { domain: "immigration", url: "https://immigrantinvest.com", name: "投资移民研究院" },
  { domain: "immigration", url: "https://www.expatica.com/moving", name: "Expatica移民指南" },
  { domain: "immigration", url: "https://www.goldenvisas.com", name: "黄金签证信息" },

  { domain: "tax", url: "https://www.chinatax.gov.cn", name: "中国国家税务总局" },
  { domain: "tax", url: "https://www.safe.gov.cn", name: "国家外汇管理局" },
  { domain: "tax", url: "https://www.ato.gov.au", name: "澳大利亚税务局" },
  { domain: "tax", url: "https://www.irs.gov", name: "美国国税局" },
  { domain: "tax", url: "https://www.gov.uk/government/organisations/hm-revenue-customs", name: "英国税务局" },
  { domain: "tax", url: "https://www.oecd.org/tax", name: "OECD税务信息" },
  { domain: "tax", url: "https://taxsummaries.pwc.com", name: "普华永道全球税务总结" },
  { domain: "tax", url: "https://www.pwccn.com/zh/tax.html", name: "普华永道中国税务" },
  { domain: "tax", url: "https://www.deloitte.com/cn/zh/services/tax.html", name: "德勤中国税务" },
  { domain: "tax", url: "https://www.ey.com/zh_cn/tax", name: "安永中国税务" },
  { domain: "tax", url: "https://home.kpmg/cn/en/home/services/tax.html", name: "毕马威全球税务" },
  { domain: "tax", url: "https://www.taxfoundation.org", name: "税务基金会" },
  { domain: "tax", url: "https://nomadcapitalist.com/finance/taxes", name: "Nomad Capitalist税务" },
  { domain: "tax", url: "https://www.blevinsfranks.com", name: "欧洲税务规划" },

  { domain: "assets", url: "https://www.safe.gov.cn", name: "外管局外汇政策" },
  { domain: "assets", url: "https://www.fatf-gafi.org", name: "FATF反洗钱机构" },
  { domain: "assets", url: "https://www.oecd.org/finance", name: "OECD金融信息" },
  { domain: "assets", url: "https://www.bis.org", name: "国际清算银行" },
  { domain: "assets", url: "https://www.hkex.com.hk", name: "香港交易所" },
  { domain: "assets", url: "https://nomadcapitalist.com/finance", name: "Nomad Capitalist资产配置" },
  { domain: "assets", url: "https://www.sovereignman.com", name: "Sovereign Man资产自由" },
  { domain: "assets", url: "https://flagtheory.com", name: "Flag Theory多旗理论" },
  { domain: "assets", url: "https://www.offshorecitizen.net", name: "离岸公民资产配置" },
  { domain: "assets", url: "https://www.assetprotectionplanners.com", name: "资产保护规划师" },
  { domain: "assets", url: "https://www.henleyglobal.com/residence-investment", name: "Henley投资移民" },
  { domain: "assets", url: "https://www.internationalliving.com/finance", name: "国际生活财务指南" },
  { domain: "assets", url: "https://www.rawlslaw.com", name: "离岸资产保护法律" },
  { domain: "assets", url: "https://www.moneyhero.com.hk", name: "香港金融产品比较" },

  { domain: "banking", url: "https://www.federalreserve.gov", name: "美联储" },
  { domain: "banking", url: "https://www.ecb.europa.eu", name: "欧洲央行" },
  { domain: "banking", url: "https://www.apra.gov.au", name: "澳大利亚审慎监管局" },
  { domain: "banking", url: "https://www.hsbc.com.hk", name: "汇丰香港开户指南" },
  { domain: "banking", url: "https://www.sc.com/hk", name: "渣打香港开户指南" },
  { domain: "banking", url: "https://www.dbs.com.hk", name: "星展香港开户指南" },
  { domain: "banking", url: "https://www.airwallex.com", name: "Airwallex企业账户" },
  { domain: "banking", url: "https://www.wise.com", name: "Wise境外账户" },
  { domain: "banking", url: "https://www.revolut.com", name: "Revolut数字银行" },
  { domain: "banking", url: "https://www.n26.com", name: "N26欧洲数字银行" },
  { domain: "banking", url: "https://www.globalbanks.com", name: "Global Banks开户指南" },
  { domain: "banking", url: "https://www.offshorebankingreviews.com", name: "离岸银行评测" },
  { domain: "banking", url: "https://www.bankaccountopening.com", name: "境外开户指南" },

  { domain: "offshore", url: "https://www.bvifsc.vg", name: "BVI金融服务委员会" },
  { domain: "offshore", url: "https://www.cima.ky", name: "开曼群岛金融管理局" },
  { domain: "offshore", url: "https://www.iomfsa.im", name: "马恩岛金融监管局" },
  { domain: "offshore", url: "https://www.cr.gov.hk/en/companies/doingBusiness.htm", name: "香港公司注册指南" },
  { domain: "offshore", url: "https://www.guidemesingapore.com", name: "新加坡公司注册指南" },
  { domain: "offshore", url: "https://www.incorporations.io", name: "全球公司注册比较" },
  { domain: "offshore", url: "https://www.offshorecitizen.net/offshore-companies", name: "离岸公司选择指南" },
  { domain: "offshore", url: "https://www.companyformations.co.uk", name: "英国公司注册" },
  { domain: "offshore", url: "https://www.offshorecorpus.com", name: "离岸公司数据库" },

  { domain: "legal", url: "https://www.mlaw.gov.sg", name: "新加坡法律部" },
  { domain: "legal", url: "https://www.justice.gov.au", name: "澳大利亚司法部" },
  { domain: "legal", url: "https://www.gov.uk/government/organisations/ministry-of-justice", name: "英国司法部" },
  { domain: "legal", url: "https://www.justice.gov", name: "美国司法部" },
  { domain: "legal", url: "https://www.hklii.hk", name: "香港法律信息研究所" },
  { domain: "legal", url: "https://sso.agc.gov.sg", name: "新加坡法规数据库" },
  { domain: "legal", url: "https://www.legal500.com", name: "Legal 500律所排名" },
  { domain: "legal", url: "https://www.lexology.com", name: "Lexology法律资讯" },
  { domain: "legal", url: "https://www.globallegalinsights.com", name: "全球法律洞察" },
  { domain: "legal", url: "https://www.internationallawoffice.com", name: "国际法律办公室" },

  { domain: "education", url: "https://www.studyinaustralia.gov.au", name: "澳大利亚留学" },
  { domain: "education", url: "https://www.singaporeedu.gov.sg", name: "新加坡教育部留学" },
  { domain: "education", url: "https://www.educationusa.state.gov", name: "美国留学" },
  { domain: "education", url: "https://www.study-uk.britishcouncil.org", name: "英国留学" },
  { domain: "education", url: "https://www.studyinnewzealand.govt.nz", name: "新西兰留学" },
  { domain: "education", url: "https://www.study.eu", name: "欧洲留学指南" },
  { domain: "education", url: "https://www.mastersportal.eu", name: "欧洲硕士项目库" },
  { domain: "education", url: "https://www.studying-in-germany.org", name: "德国留学指南" },
  { domain: "education", url: "https://www.campusfrance.org", name: "法国留学官网" },
  { domain: "education", url: "https://www.studyinholland.nl", name: "荷兰留学官网" },
  { domain: "education", url: "https://www.studyinsweden.se", name: "瑞典留学官网" },
  { domain: "education", url: "https://www.jasso.or.jp/en", name: "日本留学支援机构" },
  { domain: "education", url: "https://www.studyinkorea.go.kr", name: "韩国留学官网" },
  { domain: "education", url: "https://www.ucas.com", name: "英国大学联合招生" },
  { domain: "education", url: "https://www.commonapp.org", name: "美国大学联合申请" },
  { domain: "education", url: "https://www.ielts.org", name: "雅思官网" },
  { domain: "education", url: "https://www.toefl.org", name: "托福官网" },
  { domain: "education", url: "https://www.chineseschool.net", name: "中国国际学校网络" },
  { domain: "education", url: "https://www.cdpf.org.cn", name: "中国民办教育协会" },

  { domain: "medical", url: "https://www.nhc.gov.cn", name: "国家卫生健康委员会" },
  { domain: "medical", url: "https://www.nmpa.gov.cn", name: "国家药品监督管理局" },
  { domain: "medical", url: "https://www.dxy.cn", name: "丁香园医疗信息" },
  { domain: "medical", url: "https://www.haodf.com", name: "好大夫在线" },
  { domain: "medical", url: "https://www.guahao.com", name: "微医挂号平台" },
  { domain: "medical", url: "https://www.health.gov.au", name: "澳大利亚卫生部" },
  { domain: "medical", url: "https://www.nhs.uk", name: "英国国家医疗服务" },
  { domain: "medical", url: "https://www.bumrungrad.com", name: "泰国康民医院" },
  { domain: "medical", url: "https://www.samitivejhospitals.com", name: "泰国三美泰医院" },
  { domain: "medical", url: "https://www.bumrungrad.com/en/packages", name: "泰国康民医疗套餐" },
  { domain: "medical", url: "https://www.medparkhospital.com", name: "泰国美德帕医院" },
  { domain: "medical", url: "https://www.rafflesmedicalgroup.com", name: "新加坡莱佛士医疗" },
  { domain: "medical", url: "https://www.tokyomed.jp", name: "日本东京医疗中心" },
  { domain: "medical", url: "https://www.samsunghospital.com/global", name: "韩国三星医疗中心" },
  { domain: "medical", url: "https://www.medicaltourism.com", name: "全球医疗旅游协会" },
  { domain: "medical", url: "https://www.drugs.com", name: "Drugs.com药物数据库" },
  { domain: "medical", url: "https://www.webmd.com", name: "WebMD医疗信息" },
  { domain: "medical", url: "https://www.rxlist.com", name: "RxList药物参考" },
  { domain: "medical", url: "https://www.chemistdirect.co.uk", name: "英国网上药房" },
  { domain: "medical", url: "https://www.iherb.com", name: "iHerb保健品购买" },
];
